<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX0py77g\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX0py77g/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX0py77g.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX0py77g\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX0py77g\App_KernelDevDebugContainer([
    'container.build_hash' => 'X0py77g',
    'container.build_id' => '1ae434d8',
    'container.build_time' => 1618502171,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX0py77g');
